version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/work

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t silentkevin/example-for-groovy-long-bug:latest -f docker/Dockerfile .
      - run: docker tag silentkevin/example-for-groovy-long-bug:latest silentkevin/example-for-groovy-long-bug:$CIRCLE_SHA1
      - run: docker push silentkevin/example-for-groovy-long-bug:$CIRCLE_SHA1
      - run: docker push silentkevin/example-for-groovy-long-bug:latest
