version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/work

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker
      - run: bash ./docker_build_and_run.sh
